apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntuserver
  labels:
    os: ubuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      os: ubuntu
  template:
    metadata:
      labels:
        os:  ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        resources:
          limits:
            memory: "500m"
            cpu: "500m"
        ports:
          - containerPort: 8080