apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntuserver
  labels:
    os: ubuntu
spec:
  replicas: 2
  selector:
    matchLabels:
      os: ubuntu
  template:
    metadata:
      labels:
        os:  ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
      - name: ubuntu2
        image: ubuntu
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        command: ["/bin/bash", "-C"]
        args:
          - sleep 300